### ISSUE TITLE
不能检测

### ISSUE THREAD

**Issue by zs1103** [wuyuanyi135/XposedHuaweiHeartBypass#1]
试过了  这个跟机型伪装一样可以通过华为检测  但是依旧不能用  应该华为还有其他限
制条件

**Comment by wuyuanyi135** [comment]
@zs1103 请问什么功能不能用？
另外 请告知软件版本

**Comment by zs1103** [comment]
很抱歉    能用了  感谢回复



发自我的小米手机在 wuyuanyi135 <notifications@github.com>，2020年5月28日 19:44写道：

@zs1103 开启时是否有看到Toast 显示 Device check bypassed?

另外 请告知软件版本



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/wuyuanyi135/XposedHuaweiHeartBypass/issues/1#issuecomment-635288875",

"url": "https://github.com/wuyuanyi135/XposedHuaweiHeartBypass/issues/1#issuecomment-635288875",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by wuyuanyi135** [comment]
Resolved
