### ISSUE TITLE
大佬有时间把血管健康app也做了吗

### ISSUE THREAD

**Issue by mojave-pku** [wuyuanyi135/XposedHuaweiHeartBypass#4]
rt，心脏健康已上车，好使！

**Comment by wuyuanyi135** [comment]
@mojave-pku 没听说过这个app，也是华为手表的DLC吗？

**Comment by mojave-pku** [comment]
对，gt2pro用的

**Comment by ruigemen** [comment]
同等解决

**Comment by greenyi1984** [comment]
跪求大佬搞定血管研究app

**Comment by wuyuanyi135** [comment]
@greenyi1984 谢谢关注。我在4月有时间试试。由于没有设备，到时候可能需要帮忙测试。

**Comment by greenyi1984** [comment]
> 
> 
> @greenyi1984 谢谢关注。我在4月有时间试试。由于没有设备，到时候可能需要帮忙测试。

好的

**Comment by mojave-pku** [comment]
> @greenyi1984 谢谢关注。我在4月有时间试试。由于没有设备，到时候可能需要帮忙测试。

期待，需要测试可以喊我！

**Comment by wuyuanyi135** [comment]
@mojave-pku @greenyi1984 @ruigemen Please refer to https://github.com/wuyuanyi135/XposedHuaweiVascularBypass and test the patch for Huawei vascular app.
